name: 'Compiler Log Action'
description: 'Generates and uploads compiler logs for the build'
author: 'jaredpar'

inputs:
  binlog:
    description: 'Path to the binary log' 
    required: false
    default: ''
  complog:
    description: 'Name of the compiler log to create'
    required: false
    default: 'build.complog'
  artifact:
    description: 'Name of the artifact to upload'
    required: false
    default: 'build.complog'

runs:
  using: node20
  main: dist/index.js
