name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  test-typescript:
    name: TypeScript Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Check Format
        id: npm-format-check
        run: npm run format:check

      - name: Lint
        id: npm-lint
        run: npm run lint

      - name: Test
        id: npm-ci-test
        run: npm run ci-test

  test-action:
    name: GitHub Actions Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build .NET console app
        run: dotnet build __tests__/projects/console -bl

      - name: 'Test: simple'
        id: test-action1
        uses: ./
        with: 
            artifact: 'simple.complog'

      - name: 'Test: simple2'
        id: test-action2
        uses: ./
        with: 
            binlog: 'msbuild.binlog'
            complog: 'build2.complog'
            artifact: 'simple.complog'
